#!/bin/bash

CP=/home/afs/.m2/repo/junit/junit/4.12/junit-4.12.jar:/home/afs/.m2/repo/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/afs/.m2/repo/org/apache/commons/commons-csv/1.2/commons-csv-1.2.jar:/home/afs/.m2/repo/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar:/home/afs/.m2/repo/org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.jar:/home/afs/.m2/repo/log4j/log4j/1.2.17/log4j-1.2.17.jar

# Not test
CP=/home/afs/.m2/repo/org/apache/commons/commons-csv/1.2/commons-csv-1.2.jar:/home/afs/.m2/repo/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar:/home/afs/.m2/repo/org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.jar:/home/afs/.m2/repo/log4j/log4j/1.2.17/log4j-1.2.17.jar

CP="target/classes:$CP"

java -cp "$CP" dev.DevCSV "$@"
